
name: CI-CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: live-go    # set this to your application's name

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          fabricioveronez/marvel-dex:${{github.run_number}}
          fabricioveronez/marvel-dex:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'fabricioveronez/marvel-dex:${{github.run_number}}'